services:
  skywalking-agent-test-http-4.3.2:
    environment:
    - SCENARIO_VERSION=4.3.2
    - SCENARIO_SUPPORT_FRAMEWORK=http
    - SCENARIO_ENTRY_SERVICE=http://localhost:8080/entryService
    - SCENARIO_HEALTH_CHECK_URL=http://localhost:8080/healthCheck
    image: skyapm/agent-tomcat:latest
    links:
    - mysql
    volumes:
    - /agent/path:/usr/local/skywalking-agent-scenario/agent
    - /data/path:/usr/local/skywalking-agent-scenario/data
    - /package/path:/usr/local/skywalking-agent-scenario/packages
  mysql:
    environment:
    - test:test
    - test1:test1
    image: xxxx
version: '2.1'
